language: java
jdk: openjdk11

branches:
  only:
  - develop
  - master

before_install:
- chmod +x mvnw

deploy:
  provider: cloudfoundry
  username: polushan@yandex.ru
  api: https://api.run.pivotal.io
  organization: PingPong
  space: development
  manifest: manifest.yml
  app_name: gateway
  on:
    branch: master
  password:
    secure: YcuL9kLjzritzVemJKPmBrxGJfSvA9ZiOvk58W5NuTR8YhsrW8rkR9retIjTaRE3Me4ClWsqIEMvuaWiIJB+gcufbFiKY14emaFVyqrl4ddUudTjMWXHgURH7eUAC81NsG+W5tlDE9OYOJO6NkrjlXPsWnDnS6s/8GdTTcI1/BjVm8Mhces/jeZandDOcjeWg8C+vuiZ8OlW+aQ6wtBylYkdGSt8zB/XljMrntb4bgZm6u+BCAOJQ5osjDTrtUmSgEmLfAnClNn1k49tCOJmABpTyxipkosKQSBVAy8J6W+tqoGVlvOrEVnVmwLU9cb+1z1voX+17sYcmgLnHowjL+l9s2PQSqxhD+SbDBgwBjvjMwaMexdVaYfJ89uJoDr1RAjtJ0ngEgD/UheD1QeInHHC0y7lqzxxp5X4dsLrxYKAbVzgd+1hKkrsG1F/X/FvfZbh+4WFAnfjNfahe01KHaogl243kBzupZAG5Fqb45N3dSPhpxdnkEBdqrUs01gtrGLhalZqNZgJZXWnObG+SH30c9V/DhqvXwhpL8y/7T+QoYgX5ikzYXh6IlSBpm8fQHgnCVH2fGiKHtvWhiHxDGsRyoQxrOk64gIYjkpQHEATvY5mm4GeW7dUF1loPO4gv1ODTF8/xojBTGQycSHWQbG7mFOLu1VEMAPkxBg6KlY=
