eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://discovery-cheerful-fox.cfapps.io/eureka
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ping-service
          uri: lb://ping-service
          predicates:
            - Path=/ping/**
        - id: pong-service
          uri: lb://pong-service
          predicates:
            - Path=/pong/**
        - id: pingpong-view
          uri: lb://pingpong-view
          predicates:
            - Path=/view/**